# Generated by Django 2.2.19 on 2023-10-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20231006_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(related_name='recipes', to='courses.Lesson', verbose_name='уроки'),
        ),
    ]
